version: '3.8'

services:
  postgres-db:
    container_name: postgres-db
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgrespw
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '1'
          memory: 1G
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: always

  slowpoke-service:
    container_name: slowpoke-service
    depends_on:
      - postgres-db
    image: mbllllb/slowpoke:0.0.5
    ports:
      - "8080:8080"
      - "8051:8051"
    environment:
      - JAVA_OPTS=-Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.port=8051 -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.rmi.port=8051 -Djava.rmi.server.hostname=localhost -XX:ReservedCodeCacheSize=128M
    deploy:
      resources:
        limits:
          cpus: '1.2'
          memory: 1536M
        reservations:
          cpus: '1'
          memory: 1G
    restart: always

  web-service:
    container_name: web-service
    depends_on:
      - postgres-db
      - slowpoke-service
    image: mbllllb/web:0.0.5
    ports:
      - "8081:8080"
      - "8052:8052"
    environment:
      - JAVA_OPTS=-Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.port=8052 -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.rmi.port=8052 -Djava.rmi.server.hostname=localhost -XX:ReservedCodeCacheSize=128M
      - HIKARI_MAXIMUM_POOL_SIZE=10
      - TOMCAT_MAX_CONNECTIONS=8192
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '1'
          memory: 1G
    restart: always

  webflux-service:
    container_name: webflux-service
    depends_on:
      - postgres-db
      - slowpoke-service
    image: mbllllb/webflux:0.0.5
    ports:
      - "8082:8080"
      - "8053:8053"
    environment:
      - JAVA_OPTS=-Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.port=8053 -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.rmi.port=8053 -Djava.rmi.server.hostname=localhost -XX:ReservedCodeCacheSize=128M
      - PENDING_ACQUIRE_MAX_COUNT=1000
      - MAX_CONNECTIONS=12
      - RESPONSE_TIMEOUT=4s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '1'
          memory: 1G
    restart: always

  tickle-service:
    container_name: tickle
    image: mbllllb/tickle:0.0.1
    ports:
      - "8088:8080"
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 1G
        reservations:
          cpus: '2'
          memory: 1G
    restart: always
