spring:
  r2dbc:
    url: r2dbc:postgresql://postgres-db:5432/postgres
    username: postgres
    password: postgrespw

webflux-service:
  slowpoke-host: http://slowpoke-service:8080
  web-client-config:
    pending-acquire-max-count: ${PENDING_ACQUIRE_MAX_COUNT:1000}
    max-connections: ${MAX_CONNECTIONS:12}