spring:
  datasource:
    url: jdbc:postgresql://postgres-db:5432/postgres
    username: postgres
    password: postgrespw
    hikari:
      maximum-pool-size:


web-service:
  slowpoke-host: http://slowpoke-service:8080