# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on: [push]

env:
  IMAGE_SLOWPOKE_NAME: github-greencode1-slowpoke-tmp-image
  IMAGE_WEB_NAME: github-greencode1-webflux-tmp-image
  IMAGE_WEBFLUX_NAME: github-greencode1-webflux-tmp-image

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Maven
      run: mvn -B install --file pom.xml
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build a container image from our Spring Boot app using Paketo.io / Cloud Native Build Packs
      run: |
        cd ./slowpoke/
        mvn spring-boot:build-image -Dspring-boot.build-image.imageName=IMAGE_SLOWPOKE_NAME
        cd ../web/
        mvn spring-boot:build-image -Dspring-boot.build-image.imageName=IMAGE_WEB_NAME
        cd ../webflux/
        mvn spring-boot:build-image -Dspring-boot.build-image.imageName=IMAGE_WEBFLUX_NAME
    - name: Set Release version env variable
      run: |
        echo "RELEASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
    - name: Publish to Docker Hub
      run: |
        docker tag $IMAGE_SLOWPOKE_NAME mbllllb/slowpoke:latest
        docker tag $IMAGE_SLOWPOKE_NAME mbllllb/slowpoke:${{env.26}}
        docker tag $IMAGE_WEB_NAME mbllllb/web:latest
        docker tag $IMAGE_WEB_NAME mbllllb/web:${{env.RELEASE_VERSION}}
        docker tag $IMAGE_WEBFLUX_NAME mbllllb/webflux:latest
        docker tag $IMAGE_WEBFLUX_NAME mbllllb/webflux:${{env.RELEASE_VERSION}}
        
        docker push mbllllb/slowpoke:latest
        docker push mbllllb/slowpoke:${{env.RELEASE_VERSION}}        
        docker push mbllllb/web:latest
        docker push mbllllb/web:${{env.RELEASE_VERSION}}        
        docker push mbllllb/webflux:latest
        docker push mbllllb/webflux:${{env.RELEASE_VERSION}}
